"""
 * -------------------------------------------------------------
 *  GameDiary
 *  Playtime Tracking System for the PlayStation Portable (PSP)
 *
 *  Developed by OniMock
 *  © 2026 OniMock. All rights reserved.
 * -------------------------------------------------------------
"""


"""
embed_generator.py — Converts font atlas binary assets (PNG + BIN) into
C source/header files so they can be compiled directly into the EBOOT.

No file I/O at runtime — fonts are always available on real PSP hardware.
"""

import os
import struct

def binary_to_c_array(data: bytes, var_name: str) -> str:
    """Convert raw bytes to a C const array definition."""
    lines = []
    lines.append(f"const unsigned char {var_name}[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        row = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {row},")
    lines.append(f"}};")
    lines.append(f"const unsigned int {var_name}_size = {len(data)};")
    return "\n".join(lines)


def generate_header(groups: dict) -> str:
    """Generate the shared header exposing all embedded font data as page lists."""
    lines = []
    lines.append(f"/**")
    lines.append(f" * -------------------------------------------------------------")
    lines.append(f" *  GameDiary")
    lines.append(f" *  Playtime Tracking System for the PlayStation Portable (PSP)")
    lines.append(f" *")
    lines.append(f" *  Developed by OniMock")
    lines.append(f" *  (c) 2026 OniMock. All rights reserved.")
    lines.append(f" * -------------------------------------------------------------")
    lines.append(f"*/\n")
    lines.append("/* Auto-generated by font_pipeline. DO NOT EDIT */")
    lines.append("#ifndef FONT_EMBED_H")
    lines.append("#define FONT_EMBED_H")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    const unsigned char* png_data;")
    lines.append("    unsigned int png_size;")
    lines.append("    const unsigned char* bin_data;")
    lines.append("    unsigned int bin_size;")
    lines.append("} EmbeddedAtlas;")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    for group_name, pages in sorted(groups.items()):
        lines.append(f"/* {group_name} pages */")
        lines.append(f"extern const EmbeddedAtlas g_font_{group_name}_pages[];")
        lines.append(f"extern const int           g_font_{group_name}_page_count;")
        lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif /* FONT_EMBED_H */")
    return "\n".join(lines)


def generate_embeds(assets_dir: str, out_src_dir: str, out_inc_dir: str):
    """
    Scans assets_dir for all font_*.bin files, groups them by base name
    (e.g. latin, symbols, cjk_jp_0, cjk_jp_1) and generates C embed files.
    """
    os.makedirs(out_src_dir, exist_ok=True)
    os.makedirs(os.path.join(out_inc_dir, "app", "render"), exist_ok=True)

    # 1. Discover all font_*.bin files
    all_bin_files = [f for f in os.listdir(assets_dir) if f.startswith("font_") and f.endswith(".bin")]

    # 2. Group into base names (e.g. "cjk_jp_0" -> group "cjk_jp", page 0)
    groups = {} # base_name -> {page_idx: full_name}
    for bin_file in all_bin_files:
        full_name = bin_file[5:-4] # "cjk_jp_0"

        # Determine group and page index
        if "_" in full_name and full_name.split("_")[-1].isdigit():
            parts = full_name.split("_")
            page_idx = int(parts[-1])
            group_name = "_".join(parts[:-1])
        else:
            group_name = full_name
            page_idx = 0

        if group_name not in groups:
            groups[group_name] = {}
        groups[group_name][page_idx] = full_name

    # 3. For each group, generate the embed files and the page list
    for group_name, pages in groups.items():
        page_indices = sorted(pages.keys())
        full_names = [pages[i] for i in page_indices]

        c_lines = []
        c_lines.append(f"/**")
        c_lines.append(f" * -------------------------------------------------------------")
        c_lines.append(f" *  GameDiary")
        c_lines.append(f" *  Playtime Tracking System for the PlayStation Portable (PSP)")
        c_lines.append(f" *")
        c_lines.append(f" *  Developed by OniMock")
        c_lines.append(f" *  (c) 2026 OniMock. All rights reserved.")
        c_lines.append(f" * -------------------------------------------------------------")
        c_lines.append(f"*/\n")
        c_lines.append("/* Auto-generated by font_pipeline. DO NOT EDIT */")
        c_lines.append("#include \"app/render/font_embed.h\"\n")

        # Emit raw data arrays for each page
        for name in full_names:
            png_path = os.path.join(assets_dir, f"font_{name}.png")
            bin_path = os.path.join(assets_dir, f"font_{name}.bin")

            with open(png_path, "rb") as f:
                png_data = f.read()
            with open(bin_path, "rb") as f:
                bin_data = f.read()

            safe = name.replace("-", "_")
            c_lines.append(f"/* Page: {name} */")
            c_lines.append(binary_to_c_array(png_data, f"raw_font_{safe}_png"))
            c_lines.append(binary_to_c_array(bin_data, f"raw_font_{safe}_bin"))
            c_lines.append("")

        # Emit the page array
        c_lines.append(f"const EmbeddedAtlas g_font_{group_name}_pages[] = {{")
        for name in full_names:
            safe = name.replace("-", "_")
            c_lines.append(f"    {{ raw_font_{safe}_png, raw_font_{safe}_png_size, raw_font_{safe}_bin, raw_font_{safe}_bin_size }},")
        c_lines.append("};")
        c_lines.append(f"const int g_font_{group_name}_page_count = {len(full_names)};")

        out_file = os.path.join(out_src_dir, f"font_{group_name}_embed.c")
        with open(out_file, "w") as f:
            f.write("\n".join(c_lines))

        print(f"  [EMBED] {group_name}: {len(full_names)} pages → {out_file}")

    # 4. Write shared header
    header = generate_header(groups)
    header_path = os.path.join(out_inc_dir, "app", "render", "font_embed.h")
    with open(header_path, "w") as f:
        f.write(header)
    print(f"  [EMBED] Header → {header_path}")


if __name__ == "__main__":
    import sys
    assets  = sys.argv[1] if len(sys.argv) > 1 else "assets/fonts"
    src_out = sys.argv[2] if len(sys.argv) > 2 else "src/app/render"
    inc_out = sys.argv[3] if len(sys.argv) > 3 else "include"
    generate_embeds(assets, src_out, inc_out)
