"""
 * -------------------------------------------------------------
 *  GameDiary
 *  Playtime Tracking System for the PlayStation Portable (PSP)
 *
 *  Developed by OniMock
 *  © 2026 OniMock. All rights reserved.
 * -------------------------------------------------------------
"""


"""
embed_generator.py — Converts font atlas binary assets (PNG + BIN) into
C source/header files so they can be compiled directly into the EBOOT.

No file I/O at runtime — fonts are always available on real PSP hardware.
"""

import os
import struct

def binary_to_c_array(data: bytes, var_name: str) -> str:
    """Convert raw bytes to a C const array definition."""
    hex_bytes = ", ".join(f"0x{b:02X}" for b in data)
    lines = []
    lines.append(f"/**")
    lines.append(f" * -------------------------------------------------------------")
    lines.append(f" *  GameDiary")
    lines.append(f" *  Playtime Tracking System for the PlayStation Portable (PSP)")
    lines.append(f" *")
    lines.append(f" *  Developed by OniMock")
    lines.append(f" *  Copyright (c) 2026 OniMock. All rights reserved.")
    lines.append(f" * -------------------------------------------------------------")
    lines.append(f"*/\n")
    lines.append(f"/* Auto-generated by font_pipeline. DO NOT EDIT */")
    lines.append(f"#include \"app/render/font_embed.h\"")
    lines.append(f"")
    lines.append(f"const unsigned char {var_name}[] = {{")

    # Break into rows of 16 bytes for readability
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        row = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {row},")

    lines.append(f"}};")
    lines.append(f"const unsigned int {var_name}_size = {len(data)};")
    lines.append(f"")
    return "\n".join(lines)


def generate_header(atlas_names: list) -> str:
    """Generate the shared header exposing all embedded font data."""
    lines = []
    lines.append(f"/**")
    lines.append(f" * -------------------------------------------------------------")
    lines.append(f" *  GameDiary")
    lines.append(f" *  Playtime Tracking System for the PlayStation Portable (PSP)")
    lines.append(f" *")
    lines.append(f" *  Developed by OniMock")
    lines.append(f" *  Copyright (c) 2026 OniMock. All rights reserved.")
    lines.append(f" * -------------------------------------------------------------")
    lines.append(f"*/\n")
    lines.append("/* Auto-generated by font_pipeline. DO NOT EDIT */")
    lines.append("#ifndef FONT_EMBED_H")
    lines.append("#define FONT_EMBED_H")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    for name in atlas_names:
        safe = name.replace("-", "_")
        lines.append(f"/* {name} PNG texture data */")
        lines.append(f"extern const unsigned char font_{safe}_png[];")
        lines.append(f"extern const unsigned int  font_{safe}_png_size;")
        lines.append(f"")
        lines.append(f"/* {name} BIN metadata */")
        lines.append(f"extern const unsigned char font_{safe}_bin[];")
        lines.append(f"extern const unsigned int  font_{safe}_bin_size;")
        lines.append(f"")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif /* FONT_EMBED_H */")
    return "\n".join(lines)


def generate_embeds(assets_dir: str, out_src_dir: str, out_inc_dir: str,
                    atlas_names: list):
    """
    Reads PNG + BIN files for each atlas and writes:
      out_src_dir/font_<name>_embed.c   — byte array definitions
      out_inc_dir/app/render/font_embed.h — extern declarations
    """
    os.makedirs(out_src_dir, exist_ok=True)
    os.makedirs(os.path.join(out_inc_dir, "app", "render"), exist_ok=True)

    for name in atlas_names:
        safe = name.replace("-", "_")

        png_path = os.path.join(assets_dir, f"font_{name}.png")
        bin_path = os.path.join(assets_dir, f"font_{name}.bin")

        if not os.path.exists(png_path) or not os.path.exists(bin_path):
            print(f"  [WARN] Missing files for atlas '{name}', skipping embed.")
            continue

        with open(png_path, "rb") as f:
            png_data = f.read()
        with open(bin_path, "rb") as f:
            bin_data = f.read()

        c_src  = binary_to_c_array(png_data, f"font_{safe}_png")
        c_src += "\n"
        c_src += binary_to_c_array(bin_data, f"font_{safe}_bin")

        out_file = os.path.join(out_src_dir, f"font_{safe}_embed.c")
        with open(out_file, "w") as f:
            f.write(c_src)

        png_kb = len(png_data) / 1024
        bin_kb = len(bin_data) / 1024
        print(f"  [EMBED] {name}: PNG={png_kb:.1f}KB, BIN={bin_kb:.1f}KB → {out_file}")

    # Write shared header
    header = generate_header(atlas_names)
    header_path = os.path.join(out_inc_dir, "app", "render", "font_embed.h")
    with open(header_path, "w") as f:
        f.write(header)
    print(f"  [EMBED] Header → {header_path}")


if __name__ == "__main__":
    import sys
    assets  = sys.argv[1] if len(sys.argv) > 1 else "assets/fonts"
    src_out = sys.argv[2] if len(sys.argv) > 2 else "src/app/render"
    inc_out = sys.argv[3] if len(sys.argv) > 3 else "include"
    names   = ["latin_cyrillic", "cjk", "symbols"]
    generate_embeds(assets, src_out, inc_out, names)
