/**
 * -------------------------------------------------------------
 *  GameDiary
 *  Playtime Tracking System for the PlayStation Portable (PSP)
 *
 *  Developed by OniMock
 *  (c) 2026 OniMock. All rights reserved.
 * -------------------------------------------------------------
*/

/* Auto-generated by font_pipeline. DO NOT EDIT */
#ifndef FONT_EMBED_H
#define FONT_EMBED_H

typedef struct {
    const unsigned char* png_data;
    unsigned int png_size;
    const unsigned char* bin_data;
    unsigned int bin_size;
} EmbeddedAtlas;

#ifdef __cplusplus
extern "C" {
#endif

/* cjk_jp pages */
extern const EmbeddedAtlas g_font_cjk_jp_pages[];
extern const int           g_font_cjk_jp_page_count;

/* cjk_sc pages */
extern const EmbeddedAtlas g_font_cjk_sc_pages[];
extern const int           g_font_cjk_sc_page_count;

/* latin_cyrillic pages */
extern const EmbeddedAtlas g_font_latin_cyrillic_pages[];
extern const int           g_font_latin_cyrillic_page_count;

/* symbols pages */
extern const EmbeddedAtlas g_font_symbols_pages[];
extern const int           g_font_symbols_page_count;

#ifdef __cplusplus
}
#endif

#endif /* FONT_EMBED_H */