/**
 * -------------------------------------------------------------
 *  GameDiary
 *  Playtime Tracking System for the PlayStation Portable (PSP)
 *
 *  Developed by OniMock
 *  Copyright (c) 2026 OniMock. All rights reserved.
 * -------------------------------------------------------------
*/

/* Auto-generated by font_pipeline. DO NOT EDIT */
#ifndef FONT_EMBED_H
#define FONT_EMBED_H

#ifdef __cplusplus
extern "C" {
#endif

/* latin_cyrillic PNG texture data */
extern const unsigned char font_latin_cyrillic_png[];
extern const unsigned int  font_latin_cyrillic_png_size;

/* latin_cyrillic BIN metadata */
extern const unsigned char font_latin_cyrillic_bin[];
extern const unsigned int  font_latin_cyrillic_bin_size;

/* cjk PNG texture data */
extern const unsigned char font_cjk_png[];
extern const unsigned int  font_cjk_png_size;

/* cjk BIN metadata */
extern const unsigned char font_cjk_bin[];
extern const unsigned int  font_cjk_bin_size;

/* symbols PNG texture data */
extern const unsigned char font_symbols_png[];
extern const unsigned int  font_symbols_png_size;

/* symbols BIN metadata */
extern const unsigned char font_symbols_bin[];
extern const unsigned int  font_symbols_bin_size;

#ifdef __cplusplus
}
#endif

#endif /* FONT_EMBED_H */