/**
 * -------------------------------------------------------------
 *  GameDiary
 *  Playtime Tracking System for the PlayStation Portable (PSP)
 *
 *  Developed by OniMock
 *  © 2026 OniMock. All rights reserved.
 * -------------------------------------------------------------
 */

/**
 * @file sdf_font.c
 * @brief SDF font renderer — multi-page atlas implementation.
 *
 * The font pipeline (embed_generator.py) produces one C file per font group,
 * each exposing:
 *
 *   const EmbeddedAtlas  g_font_<group>_pages[];   // array of {png,bin} pairs
 *   const int            g_font_<group>_page_count; // number of pages
 *
 * This file flattens every page from every group into a single runtime array
 * of SDFAtlas structs, then performs glyph lookup across all of them in order.
 *
 * Fallback chain order (defined by g_group_descs[] below):
 *   latin_cyrillic → symbols → cjk_jp → cjk_sc
 */

#include "app/render/sdf_font.h"
#include "app/render/font_embed.h"
#include "app/i18n/i18n.h"
#include <pspkernel.h>
#include <pspgu.h>
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>   /* memalign() on PSP */
#include <string.h>
#include <stdint.h>
#include <png.h>
#include <math.h>

/* -----------------------------------------------------------------------
 * Binary file structures – must match exactly what font_generator.py writes
 * ----------------------------------------------------------------------- */
#pragma pack(push, 1)
typedef struct {
    char     magic[4];      /* "SDF\0" */
    uint32_t width;         /* atlas image width  (pixels) */
    uint32_t height;        /* atlas image height (pixels) */
    float    line_height;   /* em units */
    float    base_size;     /* emSize from JSON (== 32.0 for our pipeline) */
    uint32_t glyph_count;
} SDFHeader;

typedef struct {
    uint32_t codepoint;
    float u, v;   /* atlas top-left UV (0..1 normalised) */
    float w, h;   /* atlas rect size    (0..1 normalised) */
    float xoff;   /* planeBounds.left   (em units) */
    float yoff;   /* planeBounds.top    (em units, negative = above baseline) */
    float xadv;   /* horizontal advance (em units) */
} SDFGlyph;
#pragma pack(pop)

/* -----------------------------------------------------------------------
 * Runtime atlas handle (one per page)
 * ----------------------------------------------------------------------- */
typedef struct {
    SDFHeader header;
    uint16_t  lookup[65536]; /* O(1) codepoint -> glyph-array-index+1 */
    SDFGlyph *glyphs;
    /* Decoded RGBA8888 texture (memalign'd, PSP cache-flushed) */
    void     *tex_data;
    int       tex_w;        /* POT width  (for sceGuTexImage) */
    int       tex_h;        /* POT height */
    int       img_w;        /* actual image width  (informational) */
    int       img_h;        /* actual image height (informational) */
    int       group_id;     /* 0: Latin, 1: Symbols, 2: JP, 3: SC */
    int       loaded;
} SDFAtlas;

/* -----------------------------------------------------------------------
 * Vertex layout: GU_TEXTURE_32BITF | GU_COLOR_8888 | GU_VERTEX_32BITF
 * ----------------------------------------------------------------------- */
typedef struct {
    float    u, v;
    uint32_t color;
    float    x, y, z;
} VertexSDF;

/* -----------------------------------------------------------------------
 * Group descriptor — maps the static arrays generated by embed_generator.py
 * to runtime entries.  Order here defines the fallback search chain.
 * ----------------------------------------------------------------------- */
typedef struct {
    const EmbeddedAtlas *pages;
    int                  page_count;
} GroupDesc;

/* Populate from the extern arrays declared in font_embed.h */
static GroupDesc g_group_descs[] = {
    { g_font_latin_cyrillic_pages, 0 },   /* will be filled at init */
    { g_font_symbols_pages,        0 },
    { g_font_cjk_jp_pages,         0 },
    { g_font_cjk_sc_pages,         0 },
};
#define NUM_GROUPS ((int)(sizeof(g_group_descs) / sizeof(g_group_descs[0])))

/* -----------------------------------------------------------------------
 * Flat atlas registry — all pages from all groups concatenated.
 * Max: 2 + 1 + 8 + 8 = 19 pages (generous upper bound)
 * ----------------------------------------------------------------------- */
#define MAX_ATLASES 32
static SDFAtlas g_atlases[MAX_ATLASES];
static int      g_atlas_count = 0;

/* Global O(1) lookup table: codepoint -> atlas_index (0xFF = missing) */
static uint8_t g_glyph_map[65536];

/* -----------------------------------------------------------------------
 * PNG memory reader (libpng callback to read from an in-memory buffer)
 * ----------------------------------------------------------------------- */
typedef struct {
    const unsigned char *data;
    unsigned int         size;
    unsigned int         pos;
} PngMemSrc;

static void png_mem_read(png_structp png, png_bytep out, png_size_t len) {
    PngMemSrc *src = (PngMemSrc *)png_get_io_ptr(png);
    if (src->pos + len > src->size) {
        png_error(png, "PNG memory read overflow");
        return;
    }
    memcpy(out, src->data + src->pos, len);
    src->pos += len;
}

/* Round up to next power of two (PSP texture requirement) */
static int next_pow2(int n) {
    int x = 1;
    while (x < n) x <<= 1;
    return x;
}

/* -----------------------------------------------------------------------
 * Decode a PNG from a byte buffer into a 16-byte-aligned RGBA8888 buffer.
 *
 * The SDF distance lives in the Red channel.  We repack it as:
 *   alpha = R (distance value)
 *   RGB   = 0xFFFFFF  (modulated by vertex color at draw time)
 *
 * This allows sceGu to use GU_TFX_MODULATE so the vertex color tints glyphs.
 * ----------------------------------------------------------------------- */
static void *decode_png(const unsigned char *png_data, unsigned int png_size,
                        int *out_w, int *out_h, int *out_tw, int *out_th)
{
    PngMemSrc mem_src = { png_data, png_size, 0 };

    png_structp png = png_create_read_struct(PNG_LIBPNG_VER_STRING,
                                              NULL, NULL, NULL);
    if (!png) return NULL;

    png_infop info = png_create_info_struct(png);
    if (!info) { png_destroy_read_struct(&png, NULL, NULL); return NULL; }

    if (setjmp(png_jmpbuf(png))) {
        png_destroy_read_struct(&png, &info, NULL);
        return NULL;
    }

    png_set_read_fn(png, &mem_src, png_mem_read);
    png_read_png(png, info,
                 PNG_TRANSFORM_STRIP_16 | PNG_TRANSFORM_PACKING |
                 PNG_TRANSFORM_EXPAND, NULL);

    int w        = (int)png_get_image_width(png, info);
    int h        = (int)png_get_image_height(png, info);
    int channels = (int)png_get_channels(png, info);
    int tw       = next_pow2(w);
    int th       = next_pow2(h);

    /* Allocate with 16-byte alignment for DMA / GE safety */
    uint32_t *buf = (uint32_t *)memalign(16, (unsigned int)(tw * th) * 4u);
    if (!buf) {
        png_destroy_read_struct(&png, &info, NULL);
        return NULL;
    }
    memset(buf, 0, (unsigned int)(tw * th) * 4u);

    png_bytep *rows = png_get_rows(png, info);
    for (int y = 0; y < h; y++) {
        for (int x = 0; x < w; x++) {
            png_bytep p = &rows[y][x * channels];
            uint8_t  r = p[0];
            /*
             * SDF distance is stored in the Red channel.
             * Format: AABBGGRR in PSP memory (little-endian RGBA in struct).
             * We want: alpha = distance, RGB = 0xFFFFFF.
             */
            buf[y * tw + x] = ((uint32_t)r << 24) | 0x00FFFFFFu;
        }
    }

    png_destroy_read_struct(&png, &info, NULL);

    *out_w = w; *out_h = h; *out_tw = tw; *out_th = th;
    sceKernelDcacheWritebackAll();
    return buf;
}

/* -----------------------------------------------------------------------
 * Load one atlas page from an EmbeddedAtlas record into the registry.
 * ----------------------------------------------------------------------- */
static int load_atlas_from_embed(int slot, const EmbeddedAtlas *embed, int group_id) {
    SDFAtlas *a = &g_atlases[slot];
    memset(a, 0, sizeof(SDFAtlas));
    a->group_id = group_id;

    /* --- PNG → RGBA buffer --- */
    a->tex_data = decode_png(
        embed->png_data, embed->png_size,
        &a->img_w, &a->img_h, &a->tex_w, &a->tex_h);

    if (!a->tex_data) {
        printf("sdf_font: atlas[%d] PNG decode failed\n", slot);
        return -1;
    }

    /* --- BIN: header + 65536-entry lookup + glyph array --- */
    const unsigned char *bin = embed->bin_data;
    unsigned int         sz  = embed->bin_size;
    unsigned int         off = 0;

    if (sz < sizeof(SDFHeader) + sizeof(uint16_t) * 65536) {
        printf("sdf_font: atlas[%d] BIN too small (%u bytes)\n", slot, sz);
        free(a->tex_data);
        return -1;
    }

    memcpy(&a->header, bin + off, sizeof(SDFHeader));
    off += sizeof(SDFHeader);

    if (strncmp(a->header.magic, "SDF", 3) != 0) {
        printf("sdf_font: atlas[%d] bad magic\n", slot);
        free(a->tex_data);
        return -1;
    }

    memcpy(a->lookup, bin + off, sizeof(uint16_t) * 65536);
    off += sizeof(uint16_t) * 65536;

    unsigned int glyph_bytes = a->header.glyph_count * sizeof(SDFGlyph);
    if (off + glyph_bytes > sz) {
        printf("sdf_font: atlas[%d] glyph data truncated\n", slot);
        free(a->tex_data);
        return -1;
    }

    a->glyphs = (SDFGlyph *)malloc(glyph_bytes);
    if (!a->glyphs) {
        free(a->tex_data);
        return -1;
    }
    memcpy(a->glyphs, bin + off, glyph_bytes);

    a->loaded = 1;
    return 0;
}

/* -----------------------------------------------------------------------
 * Public API
 * ----------------------------------------------------------------------- */

/**
 * sdf_font_set_assets_path — kept for API compatibility, no-op in embedded mode.
 * All data comes from compiled-in C arrays; no file path is needed.
 */
void sdf_font_set_assets_path(const char *path) {
    (void)path; /* suppress unused-parameter warning */
}

/**
 * sdf_font_init — wire up page_count fields, then iterate every group and
 * every page, loading each into the flat g_atlases[] registry.
 */
int sdf_font_init(void) {
    /* Fill in the live page counts from the generated extern vars */
    g_group_descs[0].page_count = g_font_latin_cyrillic_page_count;
    g_group_descs[1].page_count = g_font_symbols_page_count;
    g_group_descs[2].page_count = g_font_cjk_jp_page_count;
    g_group_descs[3].page_count = g_font_cjk_sc_page_count;

    memset(g_atlases, 0, sizeof(g_atlases));
    g_atlas_count = 0;

    for (int g = 0; g < NUM_GROUPS; g++) {
        const GroupDesc *grp = &g_group_descs[g];
        for (int p = 0; p < grp->page_count; p++) {
            if (g_atlas_count >= MAX_ATLASES) {
                printf("sdf_font: too many atlas pages (max %d)\n", MAX_ATLASES);
                break;
            }
            int slot = g_atlas_count;
            if (load_atlas_from_embed(slot, &grp->pages[p], g) == 0) {
                printf("sdf_font: loaded group %d page %d -> slot %d\n", g, p, slot);
                g_atlas_count++;
            } else {
                printf("sdf_font: group %d page %d failed, skipping\n", g, p);
            }
        }
    }

    sdf_font_rebuild_glyph_map();

    /* Return 0 even if some pages failed — fallback chain still works */
    return 0;
}

/* --- Language-Aware Glyph Mapping Table Rebuild --- */

static int is_cjk_block(uint32_t cp) {
    return (
        (cp >= 0x4E00 && cp <= 0x9FFF) ||   /* Unified Ideographs */
        (cp >= 0x3400 && cp <= 0x4DBF) ||   /* Extension A */
        (cp >= 0x3000 && cp <= 0x303F) ||   /* CJK Symbols/Punctuation */
        (cp >= 0xFF00 && cp <= 0xFFEF)      /* Fullwidth Forms */
    );
}

static int is_kana_block(uint32_t cp) {
    return (cp >= 0x3040 && cp <= 0x30FF); /* Hiragana & Katakana */
}

void sdf_font_rebuild_glyph_map(void) {
    memset(g_glyph_map, 0xFF, sizeof(g_glyph_map));
    int lang = i18n_current_lang();

    /* Priority Groups based on language */
    int primary_cjk   = (lang == LANG_CN) ? 3 : 2;
    int secondary_cjk = (lang == LANG_CN) ? 2 : 3;

    /* Single pass over all codepoints (BMP) to find best fit */
    for (uint32_t cp = 0; cp < 65536; cp++) {
        int best_slot = -1;

        if (is_kana_block(cp)) {
            /* Kanas ALWAYS prefer JP */
            for (int i = 0; i < g_atlas_count; i++) {
                if (g_atlases[i].group_id == 2 && g_atlases[i].lookup[cp] > 0) {
                    best_slot = i; break;
                }
            }
        } 
        else if (is_cjk_block(cp)) {
            /* CJK priority chain: Primary -> Secondary -> Universal */
            for (int i = 0; i < g_atlas_count; i++) {
                if (g_atlases[i].group_id == primary_cjk && g_atlases[i].lookup[cp] > 0) {
                    best_slot = i; break;
                }
            }
            if (best_slot == -1) {
                for (int i = 0; i < g_atlas_count; i++) {
                    if (g_atlases[i].group_id == secondary_cjk && g_atlases[i].lookup[cp] > 0) {
                        best_slot = i; break;
                    }
                }
            }
        }

        /* If not found yet (or not CJK/Kana), search Universal (Latin/Symbols), then fallback to CJK */
        if (best_slot == -1) {
            /* Pass A: Latin (0) & Symbols (1) */
            for (int i = 0; i < g_atlas_count; i++) {
                if (g_atlases[i].group_id <= 1 && g_atlases[i].lookup[cp] > 0) {
                    best_slot = i; break;
                }
            }
            /* Pass B: Any script as desperate fallback */
            if (best_slot == -1) {
                for (int i = 0; i < g_atlas_count; i++) {
                    if (g_atlases[i].lookup[cp] > 0) {
                        best_slot = i; break;
                    }
                }
            }
        }

        if (best_slot != -1) g_glyph_map[cp] = (uint8_t)best_slot;
    }
}

void sdf_font_cleanup(void) {
    for (int i = 0; i < g_atlas_count; i++) {
        if (g_atlases[i].loaded) {
            free(g_atlases[i].tex_data);
            free(g_atlases[i].glyphs);
        }
        memset(&g_atlases[i], 0, sizeof(SDFAtlas));
    }
    g_atlas_count = 0;
}

/* -----------------------------------------------------------------------
 * UTF-8 decoder — advances *s past the decoded codepoint.
 * Returns the Unicode codepoint, or '?' on invalid sequences.
 * ----------------------------------------------------------------------- */
static uint32_t utf8_decode_next(const char **s) {
    uint32_t c = (unsigned char)**s;
    int extra   = 0;
    if      (c < 0x80)             { (*s)++;        return c; }
    else if ((c & 0xE0) == 0xC0)  { c &= 0x1F; extra = 1; }
    else if ((c & 0xF0) == 0xE0)  { c &= 0x0F; extra = 2; }
    else if ((c & 0xF8) == 0xF0)  { c &= 0x07; extra = 3; }
    else                           { (*s)++;        return '?'; }
    (*s)++;
    while (extra-- > 0 && **s)
        c = (c << 6) | ((unsigned char)(*(*s)++) & 0x3F);
    return c;
}

/* -----------------------------------------------------------------------
 * Glyph lookup with multi-page fallback chain.
 *
 * Walks g_atlases[] in registration order (latin → symbols → cjk_jp → cjk_sc,
 * page 0 first within each group) until the codepoint is found.
 * ----------------------------------------------------------------------- */
static SDFGlyph *get_glyph(uint32_t cp, SDFAtlas **out) {
    if (cp >= 65536) cp = '?';

    uint8_t slot = g_glyph_map[cp];
    if (slot != 0xFF) {
        *out = &g_atlases[slot];
        uint16_t g_idx = g_atlases[slot].lookup[cp];
        return &g_atlases[slot].glyphs[g_idx - 1];
    }

    /* Last-resort fallback to '?' glyph */
    cp = '?';
    slot = g_glyph_map[cp];
    if (slot != 0xFF) {
        *out = &g_atlases[slot];
        uint16_t g_idx = g_atlases[slot].lookup[cp];
        return &g_atlases[slot].glyphs[g_idx - 1];
    }

    return NULL;
}

/* -----------------------------------------------------------------------
 * Core string renderer
 *
 * px_size = desired glyph height on screen in pixels (matches the -size 24
 *           passed to msdf-atlas-gen, so px_size == 24 → 1:1 scale).
 *
 * Glyph metrics (xoff, yoff, xadv) are in EM units normalised to 24 px.
 * UV are 0..1 normalised; sceGu with GU_TEXTURE_32BITF expects pixel coords,
 * so we multiply by atlas pixel dimensions.
 * ----------------------------------------------------------------------- */
static void draw_string_internal(float x, float y, const char *str,
                                  uint32_t color, float px_size, int centered)
{
    if (!str || !*str) return;

    /* --- GU state -------------------------------------------------------- */
    sceGuEnable(GU_BLEND);
    sceGuBlendFunc(GU_ADD, GU_SRC_ALPHA, GU_ONE_MINUS_SRC_ALPHA, 0, 0);
    sceGuEnable(GU_ALPHA_TEST);
    sceGuAlphaFunc(GU_GREATER, 64, 255); /* 64–128 is a good SDF threshold */

    sceGuTexMode(GU_PSM_8888, 0, 0, 0);
    sceGuTexFilter(GU_LINEAR, GU_LINEAR);
    sceGuTexFunc(GU_TFX_MODULATE, GU_TCC_RGBA);

    /* --- Optional centering pre-pass ------------------------------------- */
    float start_x = x;
    if (centered) {
        const char *p  = str;
        float        tw = 0.0f;
        while (*p) {
            SDFAtlas *at = NULL;
            SDFGlyph *g  = get_glyph(utf8_decode_next(&p), &at);
            if (g) tw += g->xadv * px_size;
        }
        start_x = x - tw * 0.5f;
    }

    /* --- Draw pass ------------------------------------------------------- */
    float    cx           = floorf(start_x + 0.5f);
    float    cy           = floorf(y + 0.5f);
    void    *last_tex_ptr = NULL;
    const char *s         = str;

    while (*s) {
        SDFAtlas *at  = NULL;
        SDFGlyph *g   = get_glyph(utf8_decode_next(&s), &at);
        if (!g || !at) continue;

        /* Always advance the cursor, even for invisible glyphs (e.g. space) */
        float adv = g->xadv * px_size;

        if (g->w > 0.0f && g->h > 0.0f) {

            /* Rebind texture only when switching to a different atlas page */
            if (at->tex_data != last_tex_ptr) {
                sceGuTexMode(GU_PSM_8888, 0, 0, 0);
                sceGuTexImage(0, at->tex_w, at->tex_h, at->tex_w, at->tex_data);
                last_tex_ptr = at->tex_data;
            }

            /* UV in PIXEL coordinates (required by GU_TEXTURE_32BITF) */
            float tw = (float)at->tex_w;
            float th = (float)at->tex_h;
            float u0 = g->u * tw;
            float v0 = g->v * th;
            float u1 = u0 + g->w * tw;
            float v1 = v0 + g->h * th;

            /*
             * Screen rect:
             *   sx = cursor + horizontal bearing (planeBounds.left, em units)
             *   sy = baseline + vertical bearing  (planeBounds.top,  em units)
             *   sw/sh: glyph UV fraction × atlas pixel size × scale factor
             *
             * The scale factor (px_size / 24.0f) converts from the 24-px em
             * coordinate system used by msdf-atlas-gen to screen pixels.
             *
             * Pixel Snapping: Use the consistent snapped baseline (cy) and 
             * cursor (cx) to calculate position. 
             * 
             * Fix: We STOPPED rounding sy per-glyph. Rounding sy independently
             * caused 1px vertical jitter (stair-stepping) because metrics (yoff)
             * vary slightly. By using the shared snapped baseline (cy), all 
             * characters align perfectly while remaining sharp.
             */
            float sx = floorf(cx + g->xoff * px_size + 0.5f);
            float sy = cy + (g->yoff * px_size);
            float sw = floorf((g->w * (float)at->header.width)  * (px_size / 24.0f) + 0.5f);
            float sh = floorf((g->h * (float)at->header.height) * (px_size / 24.0f) + 0.5f);

            VertexSDF *v = (VertexSDF *)sceGuGetMemory(2 * sizeof(VertexSDF));
            v[0].u = u0;  v[0].v = v0;  v[0].color = color;
            v[0].x = sx;       v[0].y = sy;       v[0].z = 0;
            v[1].u = u1;  v[1].v = v1;  v[1].color = color;
            v[1].x = sx + sw;  v[1].y = sy + sh;  v[1].z = 0;

            sceGuDrawArray(GU_SPRITES,
                GU_TEXTURE_32BITF | GU_COLOR_8888 | GU_VERTEX_32BITF | GU_TRANSFORM_2D,
                2, NULL, v);
        }

        cx += adv;
    }

    sceGuDisable(GU_ALPHA_TEST);
}

/* -----------------------------------------------------------------------
 * Public drawing / measurement API
 * ----------------------------------------------------------------------- */

float sdf_font_get_width(const char *str, float size) {
    float tw = 0.0f;
    const char *p = str;
    while (*p) {
        SDFAtlas *at = NULL;
        SDFGlyph *g  = get_glyph(utf8_decode_next(&p), &at);
        if (g) tw += g->xadv * size;
    }
    return tw;
}

void sdf_font_draw_string(float x, float y, const char *str,
                          uint32_t color, float size) {
    draw_string_internal(x, y, str, color, size, 0);
}

void sdf_font_draw_string_centered(float x, float y, const char *str,
                                   uint32_t color, float size) {
    draw_string_internal(x, y, str, color, size, 1);
}
